version: '{build}-{branch}'

image: Visual Studio 2022

platform: x64

environment:
    PYTHON: "C:\\Python38-x64"
    DISTUTILS_USE_SDK: "1"

install:
   - cinst nmap
   - "%PYTHON%\\python.exe -m pip install -U pip setuptools"  # upgrade pip & setuptools first
   - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"
   - "%PYTHON%\\python.exe -m pip install -r win-requirements.txt"

build: off

test_script:
   - "%PYTHON%\\python.exe -m pytest -v"
